[package]
name = "p057_insert_interval"
version = "0.1.0"
authors = ["Mao <lcdsmao@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
